version: '3.0'
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        env_file: .env
        container_name: "a.elastic"
        volumes:
        - ${host_elastic_folder}:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "${elastic_memory_allocation}"
            - ELASTIC_USERNAME=${service_username}
            - ELASTIC_PASSWORD=${service_password}
            - xpack.security.enabled=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        env_file: .env
        container_name: "a.kibana"
        environment:
            ELASTICSEARCH_HOSTS: http://elastic:9200
            ELASTICSEARCH_USERNAME: ${service_username}
            ELASTICSEARCH_PASSWORD: ${service_password}
        ulimits:
            memlock:
                soft: -1
                hard: -1

